### ISSUE TITLE
Can not set user agent for youtube

### ISSUE THREAD

**Issue by duongvanba** [AndreyPavlenko/Fermata#137]
Hi 
I'm using version 1.8.11 
I want to use youtube webapp (which allow remote control from phone youtube.com/tv) but it need custom user agent to use (or it will redirect to www version)
But problem is I can not set UA on youtube tab (I can set on browser and tested). Can you test this 
I really need a custom UA for youtube tab page 
Thank you

**Comment by duongvanba** [comment]
You can check by change UA to this 
Mozilla/5.0 (SMART-TV; Linux; Tizen 5.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/5.0 NativeTVAds Safari/538.1

**Comment by AndreyPavlenko** [comment]
The youtube tab is only compatible with mobile version of youtube. I can disable auto redirect to the youtube tab when opening youtube.com in browser, but I'm not sure if youtube will work properly in the browser tab.

**Comment by gerikss** [comment]
Hi @AndreyPavlenko, I am trying to open tv.youtube.com in browser and it redirects to youtube tab (even if it's disabled in Addons) and since youtube tab is using mobile android user agent it doesn't open tv.youtube.com but suggests to download youtube tv android app instead. Is there any way to disable redirect from browser to youtube tab when trying to open youtube links in browser? When I switch chrome browser on my phone to desktop version i can open tv.youtube.com just fine and watch videos, i wish I could do the same in fermata browser. Thanks!
