### ISSUE TITLE
Problem with sign in Youtube account

### ISSUE THREAD

**Issue by Skyman78** [AndreyPavlenko/Fermata#186]
I cant sign in Youtube account. 

Every try in phone and car ends with attached screenshot.
![Screenshot_20220817-191403_Fermata Auto](https://user-images.githubusercontent.com/111453515/185202742-001bf97b-8c67-4e2b-8bb3-091032b69298.jpg)

Can someone solve this problem?

THX

**Comment by AndreyPavlenko** [comment]
Try switching to desktop version in the menu.

**Comment by Skyman78** [comment]
Now i have another problem... :-)

![Screenshot_20220817-192735_Fermata Auto](https://user-images.githubusercontent.com/111453515/185203993-ba070381-7102-4802-98c1-fb2ce1b0a38e.jpg)

**Comment by AndreyPavlenko** [comment]
I've the same error in desktop mode, but it works for me in the standard mode.

**Comment by fcaronte** [comment]
Seem related to security settings of your profile, try enable 2factor autentication

**Comment by quark72** [comment]
I did have the same Problem - could not login because browser is unsafe.
I tried to switch to "Destop Mode" but does not help too.
But then i tried to switch back (away) from "Desktop Mode" and as first open Google.com in Fermata-Browser and tried again for 3th time to login and.... now works properly. Confusing.....
May be help this someone.

**Comment by Gregregorovich** [comment]
> I did have the same Problem - could not login because browser is unsafe.
> I tried to switch to "Destop Mode" but does not help too.
> But then i tried to switch back (away) from "Desktop Mode" and as first open Google.com in Fermata-Browser and tried again for 3th time to login and.... now works properly. Confusing.....
> May be help this someone.

I found that I had to use the mobile site to enter my username, press next, then switch to desktop mode to enter the password. Then I can two factor authenticate.

I think this is because the mobile site requests to open some sort of built-in authentication for Android 2FA via an app, but it fails to communicate with said app.

**Comment by fcaronte** [comment]
Usually I go on Google home page and login there, then will work itself on YouTube too
