### ISSUE TITLE
M3U8 link loads into Fermata three TS streams instead

### ISSUE THREAD

**Issue by Cr4z33** [AndreyPavlenko/Fermata#309]
I've got an IPTV encoder box at home that streams out of the LAN through a M3U8 link like http://externalipaddress:8080/hls/show.m3u8.

While it works perfectly if loaded ie. into VLC for Android if I do the same into Fermata (by creating a M3U playlist) it loads three TS files instead that bring no where and end up with playback error if I try to run them.

Is there any way I can get everything working?

**Comment by AndreyPavlenko** [comment]
How do you create the playlist?

**Comment by Cr4z33** [comment]
1. Tap on the +folder icon and opt to add a new M3U playlist
2. Paste in the above M3U8 URL and check the "Video Playlist" box

I end up with three TS files:
![photo_2023-10-23_14-46-51](https://github.com/AndreyPavlenko/Fermata/assets/19343851/86464f49-2363-41b7-a396-760644823c34)

**Comment by AndreyPavlenko** [comment]
This is because you add M3U8 stream URL but not M3U playlist. You need to create the playlist first.
Create playlist.m3u file, open it in a text editor and add the following content:

```
#EXTM3U
 
#EXTINF:0,My stream
[Sample.mp3](http://externalipaddress:8080/hls/show.m3u8
```

Then, add this file as a new playlist or a TV source to the app.

Please, read here about the m3u file format - https://en.wikipedia.org/wiki/M3U#:~:text=M3U%20(MP3%20URL%20or%20Moving,a%20stream%20on%20the%20Internet.

**Comment by Cr4z33** [comment]
Thank you @AndreyPavlenko it's working great now!
