### ISSUE TITLE
Could you please add some kind of highlights for Mazda users?

### ISSUE THREAD

**Issue by hs8ysx** [AndreyPavlenko/Fermata#57]
Thank you so much for creating Fermata Auto. Could you please add some kind of highlights for YouTube so Mazda users can identify which item is currently select ed? I am using a Mazda 2 with touch screen infotainment system but the touch screen is deactivated automatically when using Android Auto. 
If you don't know what I mean please take a look at my video clip on my YouTube channel. https://youtu.be/BGFb3U2GwpE

**Comment by jcaiaffa** [comment]
hey @AndreyPavlenko thank you for the app, it's amazing! I also have a similar issue with my mazda cx30 that doesn't have a touch screen, I know you mentioned that YouTube it's only the web page, but can you inject some css styles to the focus state of the links? maybe a solid border of 1px, maybe red? I think that can work since using the dial on the car will focus the links, what do you think?

**Comment by Skylegend720** [comment]
Hi @AndreyPavlenko ,
   It's an amazing app!
   But my mazda 3 got same issue.
   Is there is any solution now?

**Comment by AndreyPavlenko** [comment]
Try this version - https://github.com/AndreyPavlenko/Fermata/releases/tag/1.9.4
